### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by djmattyg007** [cassava/lackey#1]
This looks like an cool project that I'd be interested in using, but without some documentation it's difficult for me to know whether this project is for me.

**Comment by cassava** [comment]
Hey @djmattyg007, I'm usually pretty good about documenting the binary, ie. if you run it with `--help`. I'll see about adding a proper readme though, thanks for the motivation :-D

**Comment by cassava** [comment]
Preliminary documentation done. Does this tell you what you need to know?

**Comment by djmattyg007** [comment]
Yeah, it looks good. Thanks!
